services:
  app:
    build:
      context: .
      dockerfile: src/app/Dockerfile
    container_name: telegram_bot
    restart: unless-stopped
#    ports: для дебагера
#      - "5678:5678"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:18-alpine
    container_name: telegram_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - telegram_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: telegram_redis
    restart: always
    volumes:
      - telegram_redis_data:/data
    ports:
      - "6379:6379"

volumes:
  telegram_postgres_data:
  telegram_redis_data: